### ISSUE TITLE
h

### ISSUE THREAD

**Issue by Edit5920** [Whyisthisnotavalable/n-scythe#1]
how do i get it to work

**Comment by Whyisthisnotavalable** [comment]
You paste `javascript:var r = new XMLHttpRequest(); r.open("GET", 'https://raw.githubusercontent.com/Whyisthisnotavalable/n-scythe/main/scythe.js', true); r.onloadend = function (oEvent) {new Function(r.responseText)();}; r.send();`
into your search bar when you are on a version of n-gon. You can replace scythe with sword to get the sword code.

**Comment by Edit5920** [comment]
ok thank you!
